export const projectList = [
  {
    img: "/unsplash/b.jpg",
    alt: "bathroom remodel",
    title: "Bathroom Remodel",
    location: "Folsom",
    date: "91/12/2020",
    link: "/proj1",
  },
  {
    img: "/unsplash/b.jpg",
    alt: "bathroom remodel",
    title: "Bathroom Remodel",
    location: "Folsom",
    date: "91/12/2020",
    link: "/proj1",
  },
  {
    img: "/unsplash/b.jpg",
    alt: "bathroom remodel",
    title: "Bathroom Remodel",
    location: "Folsom",
    date: "91/12/2020",
    link: "/proj1",
  },
  {
    img: "/unsplash/b.jpg",
    alt: "bathroom remodel",
    title: "Bathroom Remodel",
    location: "Folsom",
    date: "91/12/2020",
    link: "/proj1",
  },
  {
    img: "/unsplash/b.jpg",
    alt: "bathroom remodel",
    title: "Bathroom Remodel",
    location: "Folsom",
    date: "91/12/2020",
    link: "/proj1",
  },
  {
    img: "/unsplash/b.jpg",
    alt: "bathroom remodel",
    title: "Bathroom Remodel",
    location: "Folsom",
    date: "91/12/2020",
    link: "/proj6",
  },
];
